### ISSUE TITLE
Can you help explain the Module NSG

### ISSUE THREAD

**Issue by say2merohit** [Ba4bes/AzDo-Bicep#3]
I need to know and understand how you're using the NSG module in this case ?
how are you assigning the values of the NSG rules to it?
If I have 10 NSG rules to create what will be approach to do it ?
can you help pls

**Comment by Ba4bes** [comment]
Hi @say2merohit ,
I'm intending to write a blog post on how to use for-loops in Bicep and Bicep modules. I will include this use case and let you know when it is available.
If you have any other specific questions about for-loops, let me know

**Comment by say2merohit** [comment]
any idea when it will be coming?

**Comment by Ba4bes** [comment]
The blog post has been published, please find it here: <https://4bes.nl/2021/08/08/use-for-loops-in-bicep/>
does this help with your question?

**Comment by say2merohit** [comment]
Sure it Did you are a SuperStar thank you so much

**Comment by say2merohit** [comment]
Thank you so much

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
